### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Trivernis** [Trivernis/rcn-frontserver#3]
-   [x] Use more shorthand Assignments
-   [ ] POST Handler
-   [ ] Easy Integration of other applications
-   [x] Not Found page
-   [ ] An Info page of the servers resource usage
